# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Limit Does Not Exist
email: dion.fulwood@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This will serve as a log for my journey into software development, my adjustment to silicon valley, 
  and a beacon for those who believe it's not possible. From javascript to recursion, frameworks and beyond
   there is no limit because the limit does not exist.
baseurl: "http://lmtdne.github.io" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Limit_DNE
github_username:  LmtDne

# Build settings
markdown: kramdown
